plugins {
    id 'java-library'
}

description 'Minimal set of trident utility classes'

dependencies {
    implementation "io.vertx:vertx-core:$vertxVersion"
    implementation "io.netty:netty-buffer:$nettyVersion"
    implementation "com.google.guava:guava:$googleGuavaVersion"
    implementation "org.bouncycastle:bcprov-jdk18on:$bouncycastleVersion"
}

